#include "/Engine/Public/Platform.ush"

int gWaterHeightTexSzX;
int gWaterHeightTexSzY;

Texture2D<float4> gTerrainHeightTexRO;
RWTexture2D<float4> gWaterHeightTexRW;

[numthreads(8, 8, 1)]
void InitHeightCS(int3 dispatchThreadId : SV_DispatchThreadID)
{
   [branch]
    if (dispatchThreadId.x >= gWaterHeightTexSzX || dispatchThreadId.y >= gWaterHeightTexSzY)
    {
        return;
    }
    gWaterHeightTexRW[dispatchThreadId.xy] = 0.05f - gTerrainHeightTexRO[dispatchThreadId.xy].x;
}