#include "/Engine/Public/Platform.ush"

Texture2D<float> gTerrainHeightTexRO;
RWTexture2D<float> gWaterHeightTexRW;

bool isInBounds(int3 id)
{
    return id.x >= 0 && id.y >= 0 && id.x < TEX_SZ && id.y < TEX_SZ;
}

static const float gInitHeight = 0.05f;

[numthreads(8, 8, 1)]
void InitHeightCS(int3 id : SV_DispatchThreadID)
{
    [branch]
    if (isInBounds(id))
    {
        gWaterHeightTexRW[id.xy] = max(0.0f, TERRAIN_SCALE * (gInitHeight - gTerrainHeightTexRO[id.xy]));
    }
}