#include "/Engine/Public/Platform.ush"

Texture2D<float4> gWaterNormalTexRO;
Texture2D<float> gWaterFoamPrevTexRO;
RWTexture2D<float> gWaterFoamTexRW;

SamplerState gBilinearSampler;

bool isInBounds(int3 id)
{
    return id.x >= 0 && id.y >= 0 && id.x < TEX_SZ && id.y < TEX_SZ;
}

[numthreads(8, 8, 1)]
void CalcFoamCS(int3 id : SV_DispatchThreadID)
{
    [branch]
    if (isInBounds(id))
    {
        gWaterFoamTexRW[id.xy] = 0.0f;
    }
}