#include "/Engine/Public/Platform.ush"

int gWaterVelocityTexSzX;
int gWaterVelocityTexSzY;

RWTexture2D<float2> gWaterVelocityTexRW;

bool isInBounds(int3 id)
{
    return id.x >= 0 && id.y >= 0 && id.x < gWaterVelocityTexSzX && id.y < gWaterVelocityTexSzY;
}

[numthreads(8, 8, 1)]
void InitVelocityCS(int3 id : SV_DispatchThreadID)
{
    [branch]
    if (isInBounds(id))
    {
        gWaterVelocityTexRW[id.xy] = 0.0f;
    }
}